# Generated by Django 4.0.3 on 2022-04-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('AUTHOR', 'AUTHOR')], default='AUTHOR', max_length=16),
        ),
    ]
